import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
[shell]
program="/bin/bash"
args = ["-l"]
[font]
size = 16
[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
