#!/bin/sh

# We use Alacritty's default Linux config directory as our storage location here.
main() {
  if [ ! -f "$HOME"/.config/alacritty/alacritty.toml ]; then
    mkdir -p "$HOME"/.config/alacritty/themes
    git clone https://github.com/alacritty/alacritty-theme "$HOME"/.config/alacritty/themes
    ln -sf "$PWD"/"alacritty.toml" "$HOME"/".config/alacritty/alacritty.toml"
  elif [ -f "$HOME"/.config/alacritty/alacritty.toml ] && [ ! -L "$HOME"/.config/alacritty/alacritty.toml ]; then
    mv "$HOME"/.config/alacritty/alacritty.toml "$HOME/.config/alacritty/alacritty.toml.bak"
    printf "Your default alacritty.toml has been saved to alacritty.toml.bak\n"
  else
    printf "Alacritty has been installed already, quitting\n"
  fi
  exit 0
}
main "$@"
