#!/bin/bash

# We use Alacritty's default Linux config directory as our storage location here.
dir=$(cd -- "$(dirname -- "$0")">>/dev/null 2>&1 && pwd)
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
cp "$dir"/"alacritty.toml" "$HOME"/".config/alacritty/alacritty.toml"
