#!/bin/sh
# Short script to install package manager.

if [ ! -d "$HOME"/.nix-profile ]; then
  sh <(curl -L https://nixos.org/nix/install) --no-daemon && sudo printf "\nDefaults   env_keep += %s/.nix-profile/bin" "$HOME" >> /etc/sudoers || printf "Nix install failed, check if you have tar and xz installed.\n"
  . "$HOME"/.nix-profile/etc/profile.d/nix.sh
fi
