#!/bin/sh
if [ ! -f "$HOME"/.gitconfig ]; then
  echo "Type in your first and last name (no accent or special characters - e.g. 'ç'): "
  read -r full_name

  echo "Type in your email address (the one used for your work/life git account): "
  read -r email

  while true; do
    echo "Which editor would you like to use to edit git commit messages?"
    read -r edit
    if ! command -v "$edit" >> /dev/null 2>&1; then
      echo "Editor $edit is not installed in your system, git commit editor is not set up properly"
    else
      git config --global core.editor "$edit"
      break
    fi
  done
  git config --global user.email "$email"
  git config --global user.name "$full_name"
  echo "Basic git setup done, quitting"
else
  echo "Seems like there's an existing .gitconfig file in your home directory, quitting."
fi
