FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN yes | unminimize && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y --no-install-recommends \
  xz-utils \
  man-db \
  curl \
  wget \
  less \
  sudo \
  openssh-client \
  tmux \
  git \
  vim \
  neovim \
  ripgrep \
  fd-find \
  shellcheck \
  busybox \
  iputils-ping && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . /usr/share/workspace
WORKDIR /usr/share/workspace
RUN ./setup.sh -d

CMD ["/bin/bash"]
