FROM archlinux:latest

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN printf "\nen_US.UTF-8 UTF-8\n" >>/etc/locale.gen && locale-gen && \
  sed -i '/^NoExtract/d' /etc/pacman.conf && \
  sed -i 's/^#DisableSandboxSyscalls/DisableSandboxSyscalls/' /etc/pacman.conf && \
  pacman -Syu --noconfirm && \
  pacman -Qqn | pacman -S --noconfirm - && \
  pacman -S --noconfirm \
  man-db \
  texinfo \
  curl \
  wget \
  vim \
  neovim \
  tmux \
  shellcheck \
  git \
  openssh \
  fd \
  ripgrep \
  unzip \
  less \
  busybox \
  bash-completion \
  starship \
  lazygit && \
  ln -sf /usr/bin/vim /usr/bin/vi && \
  pacman -Scc --noconfirm

COPY . /usr/share/workspace
WORKDIR /usr/share/workspace
RUN ./setup.sh -d

CMD ["/bin/bash"]
