FROM fedora:latest

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN sed -i '/^tsflags=nodocs/d' /etc/dnf/dnf.conf && \
  dnf -y update && \
  dnf -y reinstall "*" && \
  dnf -y install \
  man-db \
  man-pages \
  info \
  procps-ng \
  iputils \
  iproute \
  vim \
  neovim \
  git \
  busybox \
  tmux \
  ShellCheck \
  wget \
  curl \
  less \
  xz \
  ripgrep \
  fd-find && \
  dnf clean all

COPY . /usr/share/workspace
WORKDIR /usr/share/workspace
RUN ./setup.sh -d

CMD ["/bin/bash"]
