#!/bin/bash

# Sets up bash profile, vimrc and more. Always WIP.
set -e
echo "Starting Setup..." && sleep 1
# if there's a bashrc already and it isn't a link, check the following.
if [ -f $HOME/.bashrc ] && [ ! -L $HOME/.bashrc ]; then
  # add the sourcing line to default .bashrc if not there already
  case `grep -Fx "test -d $HOME/.bashrc && . $HOME/.bashrc.personal" "$HOME/.bashrc" >/dev/null; echo $?` in
    0)
      echo "bashrc already exists and is setup already"
      ;;
    1)
      echo "test -d $HOME/.bashrc && . $HOME/.bashrc.personal" >> $HOME/.bashrc
      # code if not found
      ;;
    *)
      echo "Unknown error, chec if grep is installed."
      # code if an error occurred
      ;;
  esac
    ln -sf "$PWD/.bashrc.personal" "$HOME/.bashrc.personal"
else
  # if no bashrc exists right now, force-link default bashrc to be default
  # bashrc
  if [ ! -f $HOME/.bashrc ]; then
    ln -sf "$PWD/.bashrc.default" "$HOME/.bashrc"
    ln -sf "$PWD/.bashrc.personal" "$HOME/.bashrc.personal"
  fi
fi

if [ -f $HOME/.profile ] && [ ! -L $HOME/.profile ]; then
  # add the sourcing line to default .profile if not there already
  case `grep -Fx "test -d $HOME/.profile && . $HOME/.profile.personal"  "$HOME/.profile" >/dev/null; echo $?` in
    0)
      echo "profile already exists and is setup already"
      ;;
    1)
      echo "test -d $HOME/.profile && . $HOME/.profile.personal" >> $HOME/.profile
      # code if not found
      ;;
    *)
      echo "Unknown error, chec if grep is installed."
      # code if an error occurred
      ;;
  esac
    ln -sf "$PWD/.profile.personal" "$HOME/.profile.personal"
else
  # if no profile exists right now, force-link default profile to be default
  # profile
  if [ ! -f $HOME/.profile ]; then
    ln -sf "$PWD/.profile.default" "$HOME/.profile"
  fi
fi
# Doesn't seem like there's typically a default .bash_aliases, so won't
# go through the same sharade. Same for .gitconfig. 
if [ -f $HOME/.bash_aliases ] && [ ! -L $HOME/.bash_aliases ]; then 
  mv $HOME/.bash_aliases $HOME/.bash_aliases.bak
fi
ln -sf "$PWD/.bash_aliases.personal" "$HOME/.bash_aliases"

for i in vim tmux; do
  cd $i && ./setup
  cd -
done
