[line_break]
disabled = true
[hostname]
ssh_only = true
[cmd_duration]
disabled = true
[gcloud]
disabled = true
[git_metrics]
disabled = false
[docker_context]
disabled = true

command_timeout = 5000
