#!/bin/bash
# package name/version may change in the future. Taken heavily from 
# https://www.masteringemacs.org/article/speed-up-emacs-libjansson-native-elisp-compilation
# https://emacs.stackexchange.com/questions/59538/compile-emacs-from-feature-native-comp-gccemacs-branch-on-ubuntu
# https://www.emacswiki.org/emacs/BuildingEmacs
# https://github.com/archlinux/svntogit-packages/blob/packages/emacs/trunk/PKGBUILD
sudo apt update && apt upgrade
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
echo "Now you need to edit /etc/apt/sources.list and uncomment all the deb-src entries"
sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
sudo apt-get update
sudo apt-get install gcc-10 libgccjit0 libgccjit-10-dev libgtk-3-dev libwebkit2gtk-4.0-dev 
sudo apt-get install libxpm-dev libgif-dev libjpeg-dev libpng-dev libtiff-dev libx11-dev libncurses5-dev automake autoconf texinfo libgnutls28-dev
sudo apt-get build-dep emacs
sudo apt-get install libjansson4 libjansson-dev
export CC="gcc-10"
cd ~ && git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs
./autogen.sh
./configure --without-compress-install --with-native-compilation --with-json --with-mailutils
-sysconfdir=/etc \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --localstatedir=/var \
    --with-cairo \
    --with-harfbuzz \
    --with-libsystemd \
    --with-modules \
    --with-x-toolkit=gtk3 \
    --with-xwidgets \
    --with-gnutls \
    --with-json \ 
    --with-harfbuzz \
    --with-imagemagick \
    --with-jpeg \
    --with-png \
    --with-rsvg \
    --with-tiff \
    --with-wide-int \
    --with-xft \
    --with-xml2 \
    --with-xpm \
    CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer" 
sudo make   NATIVE_FULL_AOT=1 -j$(nproc) 4
sudo make install
