#!/bin/sh
#
# Migrated .bash_aliases here for better compatibility.
for i in grep vi; do
  if [ ! -x "$i" ] && [ -x busybox ]; then
    alias '$i'='busybox $i'
  fi
done
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Add this for WSL corporate desktop. There's annoyance on corporate Windows.
if [ -d /proc ]; then
  version="$(cat /proc/version)"
  case "$version" in
  *microsoft*)
    alias network="sudo chattr -i /etc/resolv.conf && sudo vim /etc/resolv.conf && sudo chattr +i /etc/resolv.conf"
    ;;
  **) ;;
  esac
fi
# Try to use homebrew's vim if available. Mac's Vim is stuck at 9.0
if [ -f /opt/homebrew/bin/vim ]; then
  alias vim="/opt/homebrew/bin/vim"
fi
