#!/bin/sh
rm -rf "$HOME"/.config/nvim
pyenv uninstall neovim
rm -rf "$HOME"/.local/share/nvim

printf "Neovim configuration has been removed\n"
if [ -f "$HOME"/.config/nvim.bak ]; then
  mv "$HOME"/.config/nvim.bak "$HOME"/.config/nvim
  printf "Your Neovim configuration has been restored.\n"
fi
