#!/bin/sh
setup_nvim() {
  test -d "$HOME"/.config || mkdir -p "$HOME"/.config
  ln -sf "$PWD/nvim" "$HOME/.config"
}
main() {
  if [ ! -d "$HOME"/.config/nvim ]; then
    setup_nvim
  elif [ -d "$HOME"/.config/nvim ] && [ ! -L "$HOME"/.config/nvim ]; then
    mv "$HOME"/.config/nvim "$HOME"/.config/nvim.bak
    printf "Your Neovim config have been backed up in nvim.bak.\n"
    setup_nvim
  else
    printf "Neovim is already setup, quitting\n"
  fi
  exit 0
}
main "$@"
