#!/bin/sh
setup_nvim() {
  test -d "$HOME"/.config || mkdir -p "$HOME"/.config
  ln -sf "$PWD/nvim" "$HOME/.config"
}
setup_python_virtualenv() {
  pyenv install 3.12
  pyenv virtualenv 3.12 neovim
  pyenv global neovim
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  pyenv activate neovim
  pip install -r "$HOME"/dotfiles/nvim/requirement.txt
  pyenv deactivate
  pyenv global neovim
}
main() {
  if [ ! -d "$HOME"/.config/nvim ]; then
    setup_nvim
  elif [ -d "$HOME"/.config/nvim ] && [ ! -L "$HOME"/.config/nvim ]; then
    mv "$HOME"/.config/nvim "$HOME"/.config/nvim.bak
    printf "Your Neovim config have been backed up in nvim.bak.\n"
    setup_nvim
  else
    printf "Neovim is already setup, quitting\n"
  fi
  if [ -d "$HOME"/.pyenv ] && [ ! -f "$HOME"/.pyenv/versions/neovim/bin/python ]; then
    setup_python_virtualenv
  fi
  exit 0
}
main "$@"
