#!/bin/sh

system="$(uname -srm)"
case ${system%% *} in
Darwin)
	if [ ! -d /opt/homebrew ]; then
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	else
		printf "Homebrew is already installed, quitting"
	fi
	;;
*) printf "Not MacOS, won't install Homebrew for the user." ;;
esac
