#!/bin/bash
sudo pacman-key --init
# Some brain-dead distros have really outdated keyrings, hence why this
sudo pacman-key --refresh-keys
sudo pacman -S archlinux-keyring
sudo pacman-key --populate
sudo pacman -Syu

sudo pacman -S git tmux vim emacs-nativecomp
