#!/bin/sh
os=uname -s
case $os in 
  (Linux*)
    curl -L https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz > "$HOME"/nvim-linux64.tar.gz
    tar xzvf "$HOME"/nvim-linux64.tar.gz
    alias nvim="$HOME"/nvim-linux64/bin/nvim;;
  (Darwin*)
    curl -L https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz > "$HOME"/nvim-macos.tar.gz
    xattr -c "$HOME"/nvim-macos.tar.gz
    tar xzvf "$HOME"/nvim-macos.tar.gz
    alias nvim="$HOME"/nvim-macos/bin/nvim;;
esac
